const tableMockData = [
  {
    id: 6,
    contract_address: 'asdasdssdf',
    collection_image: null,
    collection_name: 'sdfdsfsf',
    quantity: '',
    presale_price: '',
    publicsale_price: '',
    max_mint: '',
    publicsale_mint_timestamp: '',
    presale_mint_timestamp: '',
    discord_link: '',
    discord_member: '',
    twitter_link: '',
    twitter_member: '',
    opensea_link: '',
    os_royalty: 'sdfsfddas',
    listing_fee: '',
    floor: null,
    nft_royalty: '',
    hidden: false,
    sortorder: 1,
    access_key: '',
    enable_access_key: false,
    createdAt: '2022-04-07T02:49:49.000Z',
    updatedAt: '2022-04-07T02:49:49.000Z'
  },
  {
    id: 5,
    contract_address: 'qdasdas',
    collection_image: null,
    collection_name: 'asdada',
    quantity: '12331',
    presale_price: '12312',
    publicsale_price: '123312',
    max_mint: '12331',
    publicsale_mint_timestamp: '12312',
    presale_mint_timestamp: '123123',
    discord_link: 'https://v4.mui.com/components/checkboxes/',
    discord_member: '12321',
    twitter_link: 'https://v4.mui.com/components/checkboxes/',
    twitter_member: '232',
    opensea_link: 'https://v4.mui.com/components/checkboxes/',
    os_royalty: 'asdsa',
    listing_fee: '',
    floor: null,
    nft_royalty: '',
    hidden: true,
    sortorder: 1,
    access_key: '',
    enable_access_key: true,
    createdAt: '2022-04-05T22:12:00.000Z',
    updatedAt: '2022-04-05T22:12:00.000Z'
  }
]
export default tableMockData
